apiVersion: v1
kind: Pod
metadata:
  name: env-demo
  labels:
    app: env-demo
spec:
  containers:
  - name: demo
    image: busybox:1.36
    command: ["sh", "-c", "printenv | sort; sleep 3600"]
    envFrom:
    - configMapRef:
        name: app-config
    - secretRef:
        name: app-secret
