apiVersion: v1
kind: Pod
metadata:
  name: pvc-demo-pod
spec:
  containers:
  - name: app
    image: busybox:1.36
    command: ["sh", "-c", "echo 'Hello from PVC' > /data/out.txt; sleep 3600"]
    volumeMounts:
    - mountPath: "/data"
      name: demo-volume
  volumes:
  - name: demo-volume
    persistentVolumeClaim:
      claimName: demo-pvc
