apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: fastapi
        image: fastapi-nginx-demo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /logs
          name: logs-volume
      volumes:
      - name: logs-volume
        persistentVolumeClaim:
          claimName: logs-pvc
